export interface Transaction {
  id: string;
  date: string;
  title: string;
  subtitle: string;
  category: string;
  catClass: string;
  amount: string;
  amountClass: string;
  property: string;
  highlight: boolean;
  icon?: string;
  bankAccount: string;
}

export const propertyNames = [
  "Downtown Plaza",
  "Main St. Loft",
  "Oak Ridge Estate",
] as const;

export const categoryOptions = [
  { label: "Capital Improvement", catClass: "bg-blue-50 text-blue-600" },
  { label: "Insurance", catClass: "bg-surface-container-high text-on-surface-variant" },
  { label: "Rental Income", catClass: "bg-emerald-50 text-emerald-700" },
  { label: "Utilities", catClass: "bg-teal-50 text-teal-700" },
  { label: "Office Supplies", catClass: "bg-blue-50 text-blue-600" },
  { label: "Contractor", catClass: "bg-teal-50 text-teal-700" },
  { label: "Maintenance", catClass: "bg-orange-50 text-orange-600" },
  { label: "Needs Review", catClass: "bg-amber-50 text-amber-800" },
] as const;

export const allTransactions: Transaction[] = [
  {
    id: "txn-001",
    date: "Mar 15, 2024",
    title: "Home Depot - Materials",
    subtitle: "Project #402 - Kitchen Reno",
    category: "Capital Improvement",
    catClass: "bg-blue-50 text-blue-600",
    amount: "-$2,450.00",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-002",
    date: "Mar 14, 2024",
    title: "Liberty Mutual - Premium",
    subtitle: "Policy: LP-998231",
    category: "Insurance",
    catClass: "bg-surface-container-high text-on-surface-variant",
    amount: "-$845.20",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-003",
    date: "Mar 14, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 4B - Maxwell",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$3,200.00",
    amountClass: "text-emerald-700",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-004",
    date: "Mar 13, 2024",
    title: "Stripe - Mktplace",
    subtitle: "Merchant ID: STR-0091",
    category: "Needs Review",
    catClass: "bg-amber-50 text-amber-800",
    amount: "-$1,102.55",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: true,
    icon: "psychology",
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-005",
    date: "Mar 12, 2024",
    title: "ConEd - Energy",
    subtitle: "Acc: 771-001-22",
    category: "Utilities",
    catClass: "bg-teal-50 text-teal-700",
    amount: "-$118.40",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-006",
    date: "Mar 11, 2024",
    title: "Amazon Business - Supplies",
    subtitle: "Order #114-2209831",
    category: "Office Supplies",
    catClass: "bg-blue-50 text-blue-600",
    amount: "-$234.99",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-007",
    date: "Mar 10, 2024",
    title: "Square Payment - Contractor",
    subtitle: "Inv: SQ-4410",
    category: "Contractor",
    catClass: "bg-teal-50 text-teal-700",
    amount: "-$567.00",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-008",
    date: "Mar 9, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 1 - Acme Corp",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$2,200.00",
    amountClass: "text-emerald-700",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-009",
    date: "Mar 8, 2024",
    title: "Roto-Rooter - Plumbing",
    subtitle: "Service Call #8811",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$680.00",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-010",
    date: "Mar 7, 2024",
    title: "State Farm - Premium",
    subtitle: "Policy: SF-441200",
    category: "Insurance",
    catClass: "bg-surface-container-high text-on-surface-variant",
    amount: "-$412.50",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-011",
    date: "Mar 6, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit B - Torres",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$1,350.00",
    amountClass: "text-emerald-700",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-012",
    date: "Mar 5, 2024",
    title: "Lowe's - Landscaping",
    subtitle: "Receipt #LW-009211",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$289.75",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-013",
    date: "Mar 4, 2024",
    title: "National Grid - Gas",
    subtitle: "Acc: NG-5500-18",
    category: "Utilities",
    catClass: "bg-teal-50 text-teal-700",
    amount: "-$94.20",
    amountClass: "text-on-surface",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-014",
    date: "Mar 3, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit E - Kim",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$1,450.00",
    amountClass: "text-emerald-700",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-015",
    date: "Mar 1, 2024",
    title: "HVAC Masters - Repair",
    subtitle: "Work Order #HV-3322",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$1,200.00",
    amountClass: "text-on-surface",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-016",
    date: "Mar 15, 2024",
    title: "GreenScape - Lawn Care",
    subtitle: "Monthly service",
    category: "Maintenance",
    catClass: "bg-orange-50 text-orange-600",
    amount: "-$320.00",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-017",
    date: "Mar 14, 2024",
    title: "Homeowners Insurance - Premium",
    subtitle: "Policy: HI-220145",
    category: "Insurance",
    catClass: "bg-surface-container-high text-on-surface-variant",
    amount: "-$180.00",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-018",
    date: "Mar 1, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Morrison Family",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$4,500.00",
    amountClass: "text-emerald-700",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-019",
    date: "Feb 28, 2024",
    title: "County Tax Office - Property Tax",
    subtitle: "Parcel: OR-4421",
    category: "Insurance",
    catClass: "bg-surface-container-high text-on-surface-variant",
    amount: "-$450.00",
    amountClass: "text-on-surface",
    property: "Oak Ridge Estate",
    highlight: false,
    bankAccount: "Wells Fargo Premium ····7832",
  },
  {
    id: "txn-020",
    date: "Mar 15, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenants: Units A, C, F",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$4,400.00",
    amountClass: "text-emerald-700",
    property: "Main St. Loft",
    highlight: false,
    bankAccount: "Chase Business Checking ····4521",
  },
  {
    id: "txn-021",
    date: "Mar 14, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 2 - StartupXYZ",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$1,800.00",
    amountClass: "text-emerald-700",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
  {
    id: "txn-022",
    date: "Mar 10, 2024",
    title: "Zillow - Rent Payment",
    subtitle: "Tenant: Unit 4 - Legal Associates",
    category: "Rental Income",
    catClass: "bg-emerald-50 text-emerald-700",
    amount: "+$2,000.00",
    amountClass: "text-emerald-700",
    property: "Downtown Plaza",
    highlight: false,
    bankAccount: "Amex Business Platinum ····3190",
  },
];

export function getTransactionById(id: string): Transaction | undefined {
  return allTransactions.find((t) => t.id === id);
}
