"use client";

import { useState, useRef, useCallback } from "react";

export interface PropertyFile {
  id: string;
  name: string;
  type: "pdf" | "image" | "spreadsheet" | "document";
  size: string;
  uploaded: string;
  category: string;
}

const typeIcons: Record<string, { icon: string; bg: string; text: string }> = {
  pdf: { icon: "picture_as_pdf", bg: "bg-red-50", text: "text-red-500" },
  image: { icon: "image", bg: "bg-blue-50", text: "text-blue-500" },
  spreadsheet: { icon: "table_chart", bg: "bg-emerald-50", text: "text-emerald-500" },
  document: { icon: "description", bg: "bg-teal-50", text: "text-teal-500" },
};

interface AISummary {
  overview: string;
  missing: { label: string; severity: "high" | "medium" }[];
  expiring: { label: string; date: string }[];
  score: number;
}

const expectedDocCategories = [
  { match: ["lease", "agreement"], label: "Lease Agreement", severity: "high" as const },
  { match: ["insurance"], label: "Insurance Certificate", severity: "high" as const },
  { match: ["inspection", "safety"], label: "Inspection Report", severity: "medium" as const },
  { match: ["tax", "assessment"], label: "Tax Records", severity: "medium" as const },
  { match: ["appraisal"], label: "Property Appraisal", severity: "medium" as const },
];

function generateSummary(files: PropertyFile[]): AISummary {
  if (files.length === 0) {
    return {
      overview: "No documents uploaded yet. Upload files to auto-generate a property compliance summary.",
      missing: expectedDocCategories.map((e) => ({ label: e.label, severity: e.severity })),
      expiring: [],
      score: 0,
    };
  }

  const categories = [...new Set(files.map((f) => f.category))];
  const catList =
    categories.length <= 2
      ? categories.map((c) => c.toLowerCase()).join(" and ")
      : `${categories.slice(0, -1).map((c) => c.toLowerCase()).join(", ")}, and ${categories[categories.length - 1].toLowerCase()}`;

  const dates = files.map((f) => new Date(f.uploaded));
  const latest = new Date(Math.max(...dates.map((d) => d.getTime())));
  const monthYear = latest.toLocaleDateString("en-US", { month: "long", year: "numeric" });

  const fileCatsLower = files.map((f) => f.category.toLowerCase());
  const fileNamesLower = files.map((f) => f.name.toLowerCase());
  const allText = [...fileCatsLower, ...fileNamesLower];

  const missing: AISummary["missing"] = [];
  let found = 0;
  for (const exp of expectedDocCategories) {
    const hasIt = exp.match.some((m) => allText.some((t) => t.includes(m)));
    if (hasIt) {
      found++;
    } else {
      missing.push({ label: exp.label, severity: exp.severity });
    }
  }

  const expiring: AISummary["expiring"] = [];
  const oneYearAgo = new Date();
  oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1);
  for (const f of files) {
    const d = new Date(f.uploaded);
    const catLower = f.category.toLowerCase();
    if (d < oneYearAgo && (catLower.includes("insurance") || catLower.includes("inspection") || catLower.includes("appraisal"))) {
      expiring.push({
        label: f.name,
        date: d.toLocaleDateString("en-US", { month: "short", year: "numeric" }),
      });
    }
  }

  const score = Math.round((found / expectedDocCategories.length) * 100);

  const overview = `${files.length} document${files.length !== 1 ? "s" : ""} on file \u2014 includes ${catList}. Last updated ${monthYear}.`;

  return { overview, missing, expiring, score };
}

function mockDownload(fileName: string) {
  const content = `[Mock file content for ${fileName}]\nThis is a placeholder download generated by The Wealth Architect.`;
  const blob = new Blob([content], { type: "application/octet-stream" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function PropertyFiles({ initialFiles }: { initialFiles: PropertyFile[] }) {
  const [files, setFiles] = useState<PropertyFile[]>(initialFiles);
  const [expanded, setExpanded] = useState(false);
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [uploadingFiles, setUploadingFiles] = useState<{ name: string; size: string; progress: number }[]>([]);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFiles = useCallback((fileList: FileList | null) => {
    if (!fileList) return;
    const incoming = Array.from(fileList).map((f) => ({
      name: f.name,
      size: f.size < 1024 * 1024 ? `${(f.size / 1024).toFixed(1)} KB` : `${(f.size / (1024 * 1024)).toFixed(1)} MB`,
      progress: 0,
    }));
    setUploadingFiles(incoming);

    // Simulate upload progress
    let tick = 0;
    const interval = setInterval(() => {
      tick += 1;
      const progress = Math.min(tick * 20, 100);
      setUploadingFiles((prev) => prev.map((f) => ({ ...f, progress })));
      if (progress >= 100) {
        clearInterval(interval);
        setTimeout(() => {
          const newFiles: PropertyFile[] = incoming.map((f) => ({
            id: `file-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`,
            name: f.name,
            type: f.name.endsWith(".pdf") ? "pdf" : f.name.match(/\.(png|jpg|jpeg|gif|webp)$/i) ? "image" : f.name.match(/\.(xlsx|csv)$/i) ? "spreadsheet" : "document",
            size: f.size,
            uploaded: new Date().toISOString().split("T")[0],
            category: "General",
          }));
          setFiles((prev) => [...newFiles, ...prev]);
          setUploadingFiles([]);
          setShowUploadModal(false);
        }, 400);
      }
    }, 300);
  }, []);

  const summary = generateSummary(files);

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <button
          onClick={() => setExpanded(!expanded)}
          className="flex items-center gap-2 group"
        >
          <span aria-hidden="true" className={`material-symbols-outlined text-[20px] text-on-surface-variant transition-transform duration-200 ${expanded ? "rotate-0" : "-rotate-90"}`}>
            expand_more
          </span>
          <h2 className="text-xl font-bold">Property Documents</h2>
          <span className="text-sm text-on-surface-variant font-medium">({files.length})</span>
        </button>
        <button
          onClick={() => { setExpanded(true); setShowUploadModal(true); }}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold shadow-sm transition-all bg-surface-container-lowest border border-outline-variant/20 text-on-surface hover:shadow-md"
        >
          <span aria-hidden="true" className="material-symbols-outlined text-[18px]">upload_file</span>
          Upload File
        </button>
      </div>

      {!expanded ? null : <>
      {/* AI Summary Card */}
      <div className="bg-surface-container-lowest rounded-xl shadow-[0_12px_32px_rgba(20,27,43,0.04)] border border-outline-variant/10 p-6 mb-6">
        <div className="flex items-start gap-4">
          <div className="shrink-0">
            <div className={`w-14 h-14 rounded-xl flex items-center justify-center ${
              summary.score >= 80 ? "bg-emerald-50" : summary.score >= 50 ? "bg-amber-50" : "bg-red-50"
            }`}>
              <span className={`text-xl font-extrabold ${
                summary.score >= 80 ? "text-emerald-700" : summary.score >= 50 ? "text-amber-600" : "text-red-500"
              }`}>{summary.score}%</span>
            </div>
            <p className="text-[9px] font-bold text-on-surface-variant uppercase tracking-widest text-center mt-1">Complete</p>
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 mb-2">
              <span aria-hidden="true" className="material-symbols-outlined text-primary text-[18px]">auto_awesome</span>
              <p className="text-[11px] font-bold text-primary uppercase tracking-widest">AI Document Analysis</p>
            </div>
            <p className="text-sm text-on-surface leading-relaxed">{summary.overview}</p>

            {summary.missing.length > 0 && (
              <div className="mt-4">
                <p className="text-[11px] font-bold text-on-surface-variant uppercase tracking-widest mb-2">Missing Documents</p>
                <div className="flex flex-wrap gap-2">
                  {summary.missing.map((m) => (
                    <span
                      key={m.label}
                      className={`inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[11px] font-bold ${
                        m.severity === "high"
                          ? "bg-red-50 text-red-600"
                          : "bg-amber-50 text-amber-700"
                      }`}
                    >
                      <span aria-hidden="true" className="material-symbols-outlined text-[14px]">
                        {m.severity === "high" ? "error" : "warning"}
                      </span>
                      {m.label}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {summary.expiring.length > 0 && (
              <div className="mt-4">
                <p className="text-[11px] font-bold text-on-surface-variant uppercase tracking-widest mb-2">May Need Renewal</p>
                <div className="flex flex-wrap gap-2">
                  {summary.expiring.map((e) => (
                    <span
                      key={e.label}
                      className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[11px] font-bold bg-orange-50 text-orange-600"
                    >
                      <span aria-hidden="true" className="material-symbols-outlined text-[14px]">schedule</span>
                      {e.label.replace(/_/g, " ").replace(/\.\w+$/, "")} ({e.date})
                    </span>
                  ))}
                </div>
              </div>
            )}

            {summary.score === 100 && summary.expiring.length === 0 && (
              <div className="mt-3 flex items-center gap-1.5 text-emerald-700">
                <span aria-hidden="true" className="material-symbols-outlined text-[16px]">verified</span>
                <p className="text-[12px] font-bold">All essential documents are current and on file.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* File Grid */}
      {files.length > 0 ? (
        <div className="bg-surface-container-lowest rounded-xl shadow-[0_12px_32px_rgba(20,27,43,0.04)] overflow-hidden border border-outline-variant/10">
          <div className="divide-y divide-surface">
            {files.map((file) => {
              const { icon, bg, text } = typeIcons[file.type] || typeIcons.document;
              return (
                <div
                  key={file.id}
                  className="flex items-center gap-4 px-6 py-4 hover:bg-surface-container-low/50 transition-all group"
                >
                  <div className={`w-10 h-10 rounded-lg ${bg} flex items-center justify-center shrink-0`}>
                    <span aria-hidden="true" className={`material-symbols-outlined text-[20px] ${text}`}>{icon}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-bold text-on-surface truncate">{file.name}</p>
                    <p className="text-[11px] text-on-surface-variant mt-0.5">
                      {file.category} &middot; {file.size} &middot; Uploaded {file.uploaded}
                    </p>
                  </div>
                  <button
                    onClick={() => mockDownload(file.name)}
                    className="w-8 h-8 rounded-lg flex items-center justify-center text-on-surface-variant hover:bg-primary/10 hover:text-primary transition-all opacity-0 group-hover:opacity-100"
                  >
                    <span aria-hidden="true" className="material-symbols-outlined text-[18px]">download</span>
                  </button>
                </div>
              );
            })}
          </div>
        </div>
      ) : (
        <div className="bg-surface-container-lowest rounded-xl border-2 border-dashed border-outline-variant/30 p-12 text-center">
          <span aria-hidden="true" className="material-symbols-outlined text-[40px] text-on-surface-variant/40 mb-3 block">folder_open</span>
          <p className="text-sm font-semibold text-on-surface-variant">No documents yet</p>
          <p className="text-xs text-on-surface-variant/60 mt-1">Upload lease agreements, insurance certificates, and other property documents</p>
        </div>
      )}
      </>}

      {/* Upload Modal */}
      {showUploadModal && (
        <div
          className="fixed inset-0 bg-black/30 backdrop-blur-sm z-50 flex items-center justify-center"
          onClick={() => { if (uploadingFiles.length === 0) setShowUploadModal(false); }}
        >
          <div
            className="bg-surface-container-lowest rounded-2xl p-8 w-full max-w-lg shadow-xl"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-bold text-on-surface">Upload Documents</h3>
              {uploadingFiles.length === 0 && (
                <button
                  onClick={() => setShowUploadModal(false)}
                  className="w-8 h-8 rounded-lg flex items-center justify-center text-on-surface-variant hover:bg-surface-container-low transition-all"
                >
                  <span aria-hidden="true" className="material-symbols-outlined text-[20px]">close</span>
                </button>
              )}
            </div>

            <input
              ref={fileInputRef}
              type="file"
              multiple
              accept=".pdf,.png,.jpg,.jpeg,.xlsx,.csv,.doc,.docx"
              className="hidden"
              onChange={(e) => handleFiles(e.target.files)}
            />

            {uploadingFiles.length > 0 ? (
              <div className="space-y-4">
                {uploadingFiles.map((f, i) => (
                  <div key={i} className="bg-surface-container-low rounded-xl p-4">
                    <div className="flex items-center justify-between mb-2">
                      <p className="text-sm font-semibold text-on-surface truncate">{f.name}</p>
                      <p className="text-xs text-on-surface-variant">{f.progress}%</p>
                    </div>
                    <div className="w-full h-2 bg-surface-container-high rounded-full overflow-hidden">
                      <div
                        className="h-full bg-primary rounded-full transition-all duration-300"
                        style={{ width: `${f.progress}%` }}
                      />
                    </div>
                    <p className="text-[11px] text-on-surface-variant mt-1.5">{f.size}</p>
                  </div>
                ))}
              </div>
            ) : (
              <div
                onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
                onDragLeave={() => setIsDragging(false)}
                onDrop={(e) => { e.preventDefault(); setIsDragging(false); handleFiles(e.dataTransfer.files); }}
                onClick={() => fileInputRef.current?.click()}
                className={`border-2 border-dashed rounded-xl py-12 flex flex-col items-center gap-4 cursor-pointer transition-all ${
                  isDragging
                    ? "border-primary bg-primary/5"
                    : "border-outline-variant/30 hover:border-primary/30 hover:bg-surface-container-low/50"
                }`}
              >
                <div className={`w-16 h-16 rounded-full flex items-center justify-center transition-colors ${isDragging ? "bg-primary/10" : "bg-surface-container-low"}`}>
                  <span aria-hidden="true" className={`material-symbols-outlined text-[32px] ${isDragging ? "text-primary" : "text-on-surface-variant"}`}>
                    cloud_upload
                  </span>
                </div>
                <div className="text-center">
                  <p className="text-sm font-semibold text-on-surface">
                    {isDragging ? "Drop files here" : "Drag & drop files here"}
                  </p>
                  <p className="text-xs text-on-surface-variant mt-1">or click to browse</p>
                  <p className="text-[11px] text-on-surface-variant/60 mt-3">PDF, PNG, JPG, XLSX, CSV, DOC up to 50MB</p>
                </div>
              </div>
            )}

            {uploadingFiles.length === 0 && (
              <div className="flex justify-end gap-3 mt-6">
                <button
                  onClick={() => setShowUploadModal(false)}
                  className="px-5 py-2.5 border border-outline-variant/20 rounded-xl text-sm font-semibold text-on-surface hover:bg-surface-container-low transition-all"
                >
                  Cancel
                </button>
                <button
                  onClick={() => fileInputRef.current?.click()}
                  className="px-5 py-2.5 bg-primary text-on-primary rounded-xl text-sm font-bold shadow-sm hover:shadow-md transition-all"
                >
                  Browse Files
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
